name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: abi # Environment name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use environment-specific secret
        env:
          SECRET_PASS: ${{ secrets.SECRET_PASS }}
        run: |
          echo "Deploying to the ${{ github.environment }} environment"
          # Deployment logic here
